spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: Mysql123456.
    url: jdbc:mysql://localhost:3306/springbootSpringSecurity?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.nie.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml